# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user-service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "user-service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import user_pb2 as user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12user-service.proto\x12\x0buserService\x1a\nuser.proto"*\n\x0eNewUserRequest\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User" \n\x11IdsOfUsersRequest\x12\x0b\n\x03ids\x18\x01 \x03(\x03"\x1c\n\x0cUserResponse\x12\x0c\n\x04name\x18\x01 \x01(\t"*\n\rUsersResponse\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.user.User2\xa4\x01\n\x0bUserService\x12\x46\n\nCreateUser\x12\x1b.userService.NewUserRequest\x1a\x19.userService.UserResponse"\x00\x12M\n\rGetUsersByIds\x12\x1e.userService.IdsOfUsersRequest\x1a\x1a.userService.UsersResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "user_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_NEWUSERREQUEST"]._serialized_start = 47
    _globals["_NEWUSERREQUEST"]._serialized_end = 89
    _globals["_IDSOFUSERSREQUEST"]._serialized_start = 91
    _globals["_IDSOFUSERSREQUEST"]._serialized_end = 123
    _globals["_USERRESPONSE"]._serialized_start = 125
    _globals["_USERRESPONSE"]._serialized_end = 153
    _globals["_USERSRESPONSE"]._serialized_start = 155
    _globals["_USERSRESPONSE"]._serialized_end = 197
    _globals["_USERSERVICE"]._serialized_start = 200
    _globals["_USERSERVICE"]._serialized_end = 364
# @@protoc_insertion_point(module_scope)
