# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lesson.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "lesson.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import user_pb2 as user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0clesson.proto\x12\x06lesson\x1a\nuser.proto"\x17\n\x07\x41\x64\x64ress\x12\x0c\n\x04name\x18\x01 \x01(\t":\n\x08\x41udience\x12\x0c\n\x04name\x18\x01 \x01(\t\x12 \n\x07\x61\x64\x64ress\x18\x02 \x01(\x0b\x32\x0f.lesson.Address"&\n\nLessonData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t"\xf0\x01\n\x08Schedule\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\x16\n\x0etype_of_lesson\x18\x02 \x01(\t\x12\x1c\n\x0fsubgroup_number\x18\x03 \x01(\x05H\x00\x88\x01\x01\x12"\n\x06lesson\x18\x04 \x01(\x0b\x32\x12.lesson.LessonData\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x0c\n\x04time\x18\x06 \x01(\t\x12"\n\x08\x61udience\x18\x07 \x01(\x0b\x32\x10.lesson.Audience\x12$\n\x08teachers\x18\x08 \x03(\x0b\x32\x12.user.UserFullNameB\x12\n\x10_subgroup_numberb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "lesson_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ADDRESS"]._serialized_start = 36
    _globals["_ADDRESS"]._serialized_end = 59
    _globals["_AUDIENCE"]._serialized_start = 61
    _globals["_AUDIENCE"]._serialized_end = 119
    _globals["_LESSONDATA"]._serialized_start = 121
    _globals["_LESSONDATA"]._serialized_end = 159
    _globals["_SCHEDULE"]._serialized_start = 162
    _globals["_SCHEDULE"]._serialized_end = 402
# @@protoc_insertion_point(module_scope)
