"""empty message

Revision ID: 43443837afb2
Revises: 1933a66cd3fe
Create Date: 2025-10-12 17:33:31.877919

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "43443837afb2"
down_revision: Union[str, Sequence[str], None] = "1933a66cd3fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_schedule_exceptions_schedule_id_departments"),
        "schedule_exceptions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_schedule_exceptions_schedule_id_schedules"),
        "schedule_exceptions",
        "schedules",
        ["schedule_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_schedule_exceptions_schedule_id_schedules"),
        "schedule_exceptions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_schedule_exceptions_schedule_id_departments"),
        "schedule_exceptions",
        "departments",
        ["schedule_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
