# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

from . import lesson_service_pb2 as lesson__service__pb2

GRPC_GENERATED_VERSION = "1.74.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in lesson_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class LessonServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLessons = channel.unary_unary(
            "/lessonService.LessonService/GetLessons",
            request_serializer=lesson__service__pb2.LessonsRequest.SerializeToString,
            response_deserializer=lesson__service__pb2.LessonsResponse.FromString,
            _registered_method=True,
        )
        self.GetLessonsForMonth = channel.unary_unary(
            "/lessonService.LessonService/GetLessonsForMonth",
            request_serializer=lesson__service__pb2.LessonsForMonthRequest.SerializeToString,
            response_deserializer=lesson__service__pb2.LessonsForMonthResponse.FromString,
            _registered_method=True,
        )
        self.GetLessonDetails = channel.unary_unary(
            "/lessonService.LessonService/GetLessonDetails",
            request_serializer=lesson__service__pb2.LessonDetailsRequest.SerializeToString,
            response_deserializer=lesson__service__pb2.LessonDetailsResponse.FromString,
            _registered_method=True,
        )
        self.SetStudentAttendance = channel.stream_stream(
            "/lessonService.LessonService/SetStudentAttendance",
            request_serializer=lesson__service__pb2.StudentAttendanceRequest.SerializeToString,
            response_deserializer=lesson__service__pb2.StudentAttendanceResponse.FromString,
            _registered_method=True,
        )
        self.GrantPrefectAttendancePermissions = channel.unary_unary(
            "/lessonService.LessonService/GrantPrefectAttendancePermissions",
            request_serializer=lesson__service__pb2.GrantPrefectAttendancePermissionsRequest.SerializeToString,
            response_deserializer=lesson__service__pb2.OkResponse.FromString,
            _registered_method=True,
        )
        self.GetLessonQRCodeData = channel.unary_unary(
            "/lessonService.LessonService/GetLessonQRCodeData",
            request_serializer=lesson__service__pb2.LessonDetailsRequest.SerializeToString,
            response_deserializer=lesson__service__pb2.LessonQRCodeResponse.FromString,
            _registered_method=True,
        )
        self.SelfApproveLessonAttendance = channel.unary_unary(
            "/lessonService.LessonService/SelfApproveLessonAttendance",
            request_serializer=lesson__service__pb2.SelfApproveLessonAttendanceRequest.SerializeToString,
            response_deserializer=lesson__service__pb2.OkResponse.FromString,
            _registered_method=True,
        )


class LessonServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLessons(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetLessonsForMonth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetLessonDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetStudentAttendance(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GrantPrefectAttendancePermissions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetLessonQRCodeData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SelfApproveLessonAttendance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_LessonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetLessons": grpc.unary_unary_rpc_method_handler(
            servicer.GetLessons,
            request_deserializer=lesson__service__pb2.LessonsRequest.FromString,
            response_serializer=lesson__service__pb2.LessonsResponse.SerializeToString,
        ),
        "GetLessonsForMonth": grpc.unary_unary_rpc_method_handler(
            servicer.GetLessonsForMonth,
            request_deserializer=lesson__service__pb2.LessonsForMonthRequest.FromString,
            response_serializer=lesson__service__pb2.LessonsForMonthResponse.SerializeToString,
        ),
        "GetLessonDetails": grpc.unary_unary_rpc_method_handler(
            servicer.GetLessonDetails,
            request_deserializer=lesson__service__pb2.LessonDetailsRequest.FromString,
            response_serializer=lesson__service__pb2.LessonDetailsResponse.SerializeToString,
        ),
        "SetStudentAttendance": grpc.stream_stream_rpc_method_handler(
            servicer.SetStudentAttendance,
            request_deserializer=lesson__service__pb2.StudentAttendanceRequest.FromString,
            response_serializer=lesson__service__pb2.StudentAttendanceResponse.SerializeToString,
        ),
        "GrantPrefectAttendancePermissions": grpc.unary_unary_rpc_method_handler(
            servicer.GrantPrefectAttendancePermissions,
            request_deserializer=lesson__service__pb2.GrantPrefectAttendancePermissionsRequest.FromString,
            response_serializer=lesson__service__pb2.OkResponse.SerializeToString,
        ),
        "GetLessonQRCodeData": grpc.unary_unary_rpc_method_handler(
            servicer.GetLessonQRCodeData,
            request_deserializer=lesson__service__pb2.LessonDetailsRequest.FromString,
            response_serializer=lesson__service__pb2.LessonQRCodeResponse.SerializeToString,
        ),
        "SelfApproveLessonAttendance": grpc.unary_unary_rpc_method_handler(
            servicer.SelfApproveLessonAttendance,
            request_deserializer=lesson__service__pb2.SelfApproveLessonAttendanceRequest.FromString,
            response_serializer=lesson__service__pb2.OkResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "lessonService.LessonService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "lessonService.LessonService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class LessonService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLessons(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/lessonService.LessonService/GetLessons",
            lesson__service__pb2.LessonsRequest.SerializeToString,
            lesson__service__pb2.LessonsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetLessonsForMonth(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/lessonService.LessonService/GetLessonsForMonth",
            lesson__service__pb2.LessonsForMonthRequest.SerializeToString,
            lesson__service__pb2.LessonsForMonthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetLessonDetails(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/lessonService.LessonService/GetLessonDetails",
            lesson__service__pb2.LessonDetailsRequest.SerializeToString,
            lesson__service__pb2.LessonDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SetStudentAttendance(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/lessonService.LessonService/SetStudentAttendance",
            lesson__service__pb2.StudentAttendanceRequest.SerializeToString,
            lesson__service__pb2.StudentAttendanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GrantPrefectAttendancePermissions(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/lessonService.LessonService/GrantPrefectAttendancePermissions",
            lesson__service__pb2.GrantPrefectAttendancePermissionsRequest.SerializeToString,
            lesson__service__pb2.OkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetLessonQRCodeData(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/lessonService.LessonService/GetLessonQRCodeData",
            lesson__service__pb2.LessonDetailsRequest.SerializeToString,
            lesson__service__pb2.LessonQRCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SelfApproveLessonAttendance(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/lessonService.LessonService/SelfApproveLessonAttendance",
            lesson__service__pb2.SelfApproveLessonAttendanceRequest.SerializeToString,
            lesson__service__pb2.OkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
