# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lesson-service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "lesson-service.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import lesson_pb2 as lesson__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14lesson-service.proto\x12\rlessonService\x1a\x0clesson.proto"\x1e\n\x0eLessonsRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t"4\n\x0fLessonsResponse\x12!\n\x07lessons\x18\x01 \x03(\x0b\x32\x10.lesson.Schedule")\n\x14LessonDetailsRequest\x12\x11\n\tlesson_id\x18\x01 \x01(\t"5\n\x16LessonsForMonthRequest\x12\r\n\x05month\x18\x01 \x01(\x05\x12\x0c\n\x04year\x18\x02 \x01(\x05"(\n\x17LessonsForMonthResponse\x12\r\n\x05\x64\x61tes\x18\x01 \x03(\t"\x8e\x01\n\x15LessonDetailsResponse\x12\'\n\rschedule_data\x18\x01 \x01(\x0b\x32\x10.lesson.Schedule\x12\x1c\n\x05group\x18\x02 \x01(\x0b\x32\r.lesson.Group\x12.\n\x0b\x61ttendances\x18\x03 \x03(\x0b\x32\x19.lesson.StudentAttendance2\xa6\x02\n\rLessonService\x12M\n\nGetLessons\x12\x1d.lessonService.LessonsRequest\x1a\x1e.lessonService.LessonsResponse"\x00\x12\x65\n\x12GetLessonsForMonth\x12%.lessonService.LessonsForMonthRequest\x1a&.lessonService.LessonsForMonthResponse"\x00\x12_\n\x10GetLessonDetails\x12#.lessonService.LessonDetailsRequest\x1a$.lessonService.LessonDetailsResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "lesson_service_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_LESSONSREQUEST"]._serialized_start = 53
    _globals["_LESSONSREQUEST"]._serialized_end = 83
    _globals["_LESSONSRESPONSE"]._serialized_start = 85
    _globals["_LESSONSRESPONSE"]._serialized_end = 137
    _globals["_LESSONDETAILSREQUEST"]._serialized_start = 139
    _globals["_LESSONDETAILSREQUEST"]._serialized_end = 180
    _globals["_LESSONSFORMONTHREQUEST"]._serialized_start = 182
    _globals["_LESSONSFORMONTHREQUEST"]._serialized_end = 235
    _globals["_LESSONSFORMONTHRESPONSE"]._serialized_start = 237
    _globals["_LESSONSFORMONTHRESPONSE"]._serialized_end = 277
    _globals["_LESSONDETAILSRESPONSE"]._serialized_start = 280
    _globals["_LESSONDETAILSRESPONSE"]._serialized_end = 422
    _globals["_LESSONSERVICE"]._serialized_start = 425
    _globals["_LESSONSERVICE"]._serialized_end = 719
# @@protoc_insertion_point(module_scope)
