# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import user_pb2 as user__pb2
from . import user_service_pb2 as user__service__pb2

GRPC_GENERATED_VERSION = "1.74.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in user_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UserSingIn = channel.unary_unary(
            "/userService.UserService/UserSingIn",
            request_serializer=user__service__pb2.SingInRequest.SerializeToString,
            response_deserializer=user__service__pb2.SingInResponse.FromString,
            _registered_method=True,
        )
        self.UserAuth = channel.unary_unary(
            "/userService.UserService/UserAuth",
            request_serializer=user__service__pb2.AuthRequest.SerializeToString,
            response_deserializer=user__pb2.UserData.FromString,
            _registered_method=True,
        )
        self.UserLogout = channel.unary_unary(
            "/userService.UserService/UserLogout",
            request_serializer=user__service__pb2.LogoutRequest.SerializeToString,
            response_deserializer=user__service__pb2.LogoutResponse.FromString,
            _registered_method=True,
        )


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UserSingIn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UserAuth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UserLogout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "UserSingIn": grpc.unary_unary_rpc_method_handler(
            servicer.UserSingIn,
            request_deserializer=user__service__pb2.SingInRequest.FromString,
            response_serializer=user__service__pb2.SingInResponse.SerializeToString,
        ),
        "UserAuth": grpc.unary_unary_rpc_method_handler(
            servicer.UserAuth,
            request_deserializer=user__service__pb2.AuthRequest.FromString,
            response_serializer=user__pb2.UserData.SerializeToString,
        ),
        "UserLogout": grpc.unary_unary_rpc_method_handler(
            servicer.UserLogout,
            request_deserializer=user__service__pb2.LogoutRequest.FromString,
            response_serializer=user__service__pb2.LogoutResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "userService.UserService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "userService.UserService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UserSingIn(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/userService.UserService/UserSingIn",
            user__service__pb2.SingInRequest.SerializeToString,
            user__service__pb2.SingInResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UserAuth(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/userService.UserService/UserAuth",
            user__service__pb2.AuthRequest.SerializeToString,
            user__pb2.UserData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UserLogout(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/userService.UserService/UserLogout",
            user__service__pb2.LogoutRequest.SerializeToString,
            user__service__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
