# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user-service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "user-service.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import user_pb2 as user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12user-service.proto\x12\x0buserService\x1a\nuser.proto"\r\n\x0b\x41uthRequest"0\n\rSingInRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t"=\n\x0eSingInResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x1c\n\x04user\x18\x02 \x01(\x0b\x32\x0e.user.UserData2\x8e\x01\n\x0bUserService\x12G\n\nUserSingIn\x12\x1a.userService.SingInRequest\x1a\x1b.userService.SingInResponse"\x00\x12\x36\n\x08UserAuth\x12\x18.userService.AuthRequest\x1a\x0e.user.UserData"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "user_service_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_AUTHREQUEST"]._serialized_start = 47
    _globals["_AUTHREQUEST"]._serialized_end = 60
    _globals["_SINGINREQUEST"]._serialized_start = 62
    _globals["_SINGINREQUEST"]._serialized_end = 110
    _globals["_SINGINRESPONSE"]._serialized_start = 112
    _globals["_SINGINRESPONSE"]._serialized_end = 173
    _globals["_USERSERVICE"]._serialized_start = 176
    _globals["_USERSERVICE"]._serialized_end = 318
# @@protoc_insertion_point(module_scope)
